spring:
  application:
    name: anekdoter
  threads:
    virtual:
      enabled: true
  flyway:
    locations: classpath:migrations

logging:
  level:
    org.zalando.logbook.Logbook: TRACE

anekdoter:
  client:
    deepseek:
      base-url: https://api.deepseek.com
      authorization: Bearer 1234
    chatgpt:
      base-url: https://api.deepseek.com
      authorization: Bearer 1234
  tags:
    initial:
      - вовочка
      - программисты
      - чапаев
      - жадность людей
      - лихие 90-е
      - политика
      - новый год
      - бездельничать на работе
      - уклонение от налогов
      - гопники
